# MySQL
spring:
  application:
    name: PetkaInfra
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://concourse-db:5432/test}
    username: ${DATASOURCE_USERNAME:concourse_user}
    password: ${DATASOURCE_PASSWORD:concourse_pass}
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

turkraft:
  springfilter:
    offsetdatetimeformatter:
      pattern: yyyy-MM-dd'T'HH:mm:ssXXX
