# MySQL
spring:
  application:
    name: PetkaInfra
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/test}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:petka}
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  web:
    resources:
      static-locations: classpath:/api

logging:
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        # include all endpoints
        #include: "*"
        # include specific endpoints
        include:
          - health
          - info
          - chaosmonkey

chaos:
  monkey:
    enabled: true
    watcher:
      controller: true
      restController: true
      service: true
      repository: true
      component: true

turkraft:
  springfilter:
    offsetdatetimeformatter:
      pattern: yyyy-MM-dd'T'HH:mm:ssXXX

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER:http://localhost:8082/auth}
  realm: ${KEYCLOAK_REALM:petka_realm}
  resource: petka_client
  public-client: true
  principal-attribute: preferred_username
