# MySQL
spring:
  application:
    name: PetkaInfra
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://pis_db:3306/test}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:petka}
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

turkraft:
  springfilter:
    offsetdatetimeformatter:
      pattern: yyyy-MM-dd'T'HH:mm:ssXXX
