openapi:
  petkaInfrastructureProject:
    base-path: /api

server:
  shutdown: graceful

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  application:
    name: PetkaInfra
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/pis}
    username: ${DATASOURCE_USERNAME:petka}
    password: ${DATASOURCE_PASSWORD:petka}
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  web:
    resources:
      static-locations: classpath:/api

logging:
  level:
    org:
      springframework:
        security: DEBUG

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /api.yaml

management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        # include all endpoints
        #include: "*"
        # include specific endpoints
        include:
          - health
          - info
          - chaosmonkey

chaos:
  monkey:
    enabled: true
    watcher:
      controller: true
      restController: true
      service: true
      repository: true
      component: true

turkraft:
  springfilter:
    offsetdatetimeformatter:
      pattern: yyyy-MM-dd'T'HH:mm:ssXXX

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER:http://host.docker.internal:8082/auth}
  realm: ${KEYCLOAK_REALM:petka_realm}
  resource: petka_client
  public-client: true
  principal-attribute: preferred_username
