openapi: 3.0.3
info:
  title: Petka Infrastructure Project
  description: Api first project
  termsOfService: http://helloreverb.com/terms/
  contact:
    name: Petka
    url: https://github.com/petka5/pis
    email: petar.georgiev@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: http://localhost:8080/
security:
  - ApiKeyAuth: [ ]
tags:
  - name: pets
    description: Operations over the pets.
paths:
  /pets:
    get:
      tags:
        - pets
      description: Returns all pets from the system that the user has access to
      operationId: findPets
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/sort'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/includeDeleted'
        - $ref: '#/components/parameters/includeCount'
      responses:
        200:
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetPageResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      x-api-first-handler: admin.Dashboard.methodLevel
    post:
      tags:
        - pets
      description: Creates a new pet in the store.  Duplicates are allowed
      operationId: addPet
      requestBody:
        description: Pet to add to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetRequest'
        required: true
      responses:
        200:
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      x-api-first-handler: admin.Dashboard.postHandler
      x-codegen-request-body-name: pet
  /pets/{id}:
    get:
      tags:
        - pets
      description: Returns resource by the id
      operationId: findPetById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    delete:
      tags:
        - pets
      description: deletes a single pet based on the ID supplied
      operationId: deletePet
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        204:
          description: pet deleted
          content: { }
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    x-api-first-handler: admin.Dashboard.pathLevel
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: api-key
  parameters:
    id:
      name: id
      in: path
      description: ID of the resource
      required: true
      schema:
        type: string
        format: uuid
    includeDeleted:
      name: includeDeleted
      in: query
      description: Include deleted
      required: false
      schema:
        type: boolean
        default: false
    includeCount:
      name: includeCount
      in: query
      description: Include count
      required: false
      schema:
        type: boolean
        default: false
    page:
      name: page
      in: query
      description: Result page number.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
    size:
      name: size
      in: query
      description: The size of the result page.
      required: false
      schema:
        type: integer
        format: int32
        default: 50
        maximum: 1000
    sort:
      name: sort
      in: query
      description: The name of a property to sort on and direction of sorting (asc or desc).
      required: false
      schema:
        type: string
    filter:
      name: filter
      in: query
      required: false
      allowEmptyValue: true
      schema:
        type: string
  schemas:
    PetRequest:
      required:
        - name
        - kind
        - age
        - type
      type: object
      properties:
        name:
          type: string
        kind:
          type: string
        age:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/Type'
    PetResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        kind:
          type: string
        age:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/Type'
        version:
          type: integer
          format: int64
        createDateTime:
          type: string
        updateDateTime:
          type: string
        deleted:
          type: boolean
    PetPageResponse:
      allOf:
        - $ref: '#/components/schemas/PageResponse'
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/PetResponse'
    PageResponse:
      type: object
      description: Response for Get All
      properties:
        totalElements:
          type: integer
        totalPages:
          type: integer
        numberOfElements:
          type: integer
        hasNext:
          type: boolean
        number:
          type: integer
        size:
          type: integer
    Type:
      type: string
      enum:
        - DOMESTIC
        - WILD
    errorModel:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
x-api-first-error-mapping:
  404:
    - java.util.NoSuchElementException
    - java.lang.IndexOutOfBoundsException
  406:
    - java.lang.UnsupportedOperationException
    - java.lang.IllegalArgumentException
    - java.lang.IllegalStateException
  409:
    - java.util.ConcurrentModificationException
    - java.util.EmptyStackException
  500:
    - java.sql.SQLException
