version: '3.8'

services:
  pis:
    container_name: pis
    build: ../../server
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - SERVER_PORT=8080
      - JVM_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:9000
    depends_on:
      pis_db:
        condition: service_healthy
  pis_db:
    image: mariadb:10.5.8
    container_name: db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petka
      - MYSQL_USER=petka
      - MYSQL_PASSWORD=petka
      - MYSQL_DATABASE=test
