version: '3.9'

services:
  pis:
    container_name: pis
    build: ../../server
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - SERVER_PORT=8080
      - JVM_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:9000
      - DATASOURCE_URL=jdbc:mysql://pis_db:3306/test
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=petka
    depends_on:
      - pis_db
  pis_db:
    image: mariadb:10.5.9
    container_name: pis_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petka
      - MYSQL_USER=petka
      - MYSQL_PASSWORD=petka
      - MYSQL_DATABASE=test

  concourse-db:
    container_name: concourse-db
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    container_name: concourse
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [ concourse-db ]
    ports: [ "8081:8080" ]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8081
      CONCOURSE_ADD_LOCAL_USER: petka:petka
      CONCOURSE_MAIN_TEAM_LOCAL_USER: petka
      # instead of relying on the default "detect"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      #CONCOURSE_X_FRAME_OPTIONS: allow
      #CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      #CONCOURSE_CLUSTER_NAME: petka
      #CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"

      #CONCOURSE_GARDEN_DNS_SERVER: "8.8.8.8"
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
      CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE: "true"
      #CONCOURSE_WORKER_RUNTIME: "containerd"
      #CONCOURSE_CONTAINERD_ALLOW_HOST_ACCESS: "true"
      #CONCOURSE_LOG_LEVEL: debug

  registry.local:
    container_name: registry
    image: registry
    restart: always
    ports:
      - "5000:5000"
