version: '3.8'

services:
  pis:
    container_name: pis
    build: ../../server
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - SERVER_PORT=8080
      - JVM_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:9000
