version: '3.9'

services:
  pis:
    container_name: pis
    build: ../../server
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: chaos-monkey
      JVM_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:9000
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/pis
      DATASOURCE_USERNAME: petka
      DATASOURCE_PASSWORD: petka
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: concourse, bitnami_keycloak, pis
      POSTGRES_PASSWORD: petka
      POSTGRES_USER: petka
      PGDATA: /database

  concourse:
    container_name: concourse
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [ postgres ]
    ports: [ "8081:8080" ]
    environment:
      CONCOURSE_POSTGRES_HOST: postgres
      CONCOURSE_POSTGRES_USER: petka
      CONCOURSE_POSTGRES_PASSWORD: petka
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8081
      CONCOURSE_ADD_LOCAL_USER: petka:petka
      CONCOURSE_MAIN_TEAM_LOCAL_USER: petka
      # instead of relying on the default "detect"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      #CONCOURSE_X_FRAME_OPTIONS: allow
      #CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      #CONCOURSE_CLUSTER_NAME: petka
      #CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"

      #CONCOURSE_GARDEN_DNS_SERVER: "8.8.8.8"
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
      CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE: "true"
      #CONCOURSE_WORKER_RUNTIME: "containerd"
      #CONCOURSE_CONTAINERD_ALLOW_HOST_ACCESS: "true"
      #CONCOURSE_LOG_LEVEL: debug

  registry.local:
    container_name: registry
    image: registry
    restart: always
    ports:
      - "5000:5000"

  keycloak:
    container_name: keycloak
    image: bitnami/keycloak
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_HTTP_PORT: 9990
      KEYCLOAK_ADMIN_USER: petka
      KEYCLOAK_ADMIN_PASSWORD: petka
      KEYCLOAK_MANAGEMENT_USER: petka
      KEYCLOAK_MANAGEMENT_PASSWORD: petka
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_USER: petka
      KEYCLOAK_DATABASE_PASSWORD: petka
